services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
    depends_on:
      - api
    networks:
      - app-network

  api:
    build: ./api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge